### ISSUE TITLE
Napisać testy

### ISSUE THREAD

**Issue by Danon** [fuzionu/consoleApp#1]
- Test pod `set` + `show`
- Test pod `set` + `delete` + `show`
- Test pod `set daniel` + `set DaNiEl` - ma być error
- Test pod `remove` + `remove` - ma się pokazać że name już wcześniej był pusty

**Comment by fuzionu** [comment]
#1 line 126 (shouldShowChangedName)
#2 line 140 (shouldDeleteSetName)
#3 line 155 (shouldNotAllowSettingTheSameNameWithDifferentCase)
#4 line 69 ( ͡° ͜ʖ ͡°) (shouldNotAllowDeletingEmptyName)
