### ISSUE TITLE
Application allows for name "D#@!$%el"

### ISSUE THREAD

**Issue by Danon** [fuzionu/consoleApp#4]
Due date: 22:00 21.10.2019

+ Tests

**Comment by fuzionu** [comment]
no more

**Comment by Danon** [comment]
Ta, you wish

**Comment by Danon** [comment]
I zmień nazwę funkcji `only_letters`, bo ona zwraca `true` wtedy jak **jest** coś oprócz litery, i `false` jak nie ma. Więc:

 - Albo zmień nazwę funkcji na `not_only_letters`
 - Albo (co uważam za lepsze) dopisz `!` w funkcji, żeby zwracalo `true` tylko jak są tylko litery (czyli odwrotnie niż teraz).

**Comment by fuzionu** [comment]
fixed
