### ISSUE TITLE
Write the application

### ISSUE THREAD

**Issue by Danon** [fuzionu/consoleApp#5]
Due date: 22:00 21.10.2019

**Comment by Danon** [comment]
Due date changes to: 21:00 23.10.2019

**Comment by Danon** [comment]
Czemu `help_message` jest znowu zmienną, zamiast funkcją? To samo było w javie i dokladnie to samo w pythonie.

Czemu wszystko dzieje się w globalnym skrypcie, zamiast w funkcji? Nie ma teraz do tego jak napisać testów.

**Comment by Danon** [comment]
Zamień komunikaty błędów:
 - `List is empty!` na `The list is already empty.`
 - `Name is already on the list!` na `Name "{wstaw imię}" is already on the list.`

Ogólnie pozamieniaj te wykrzykniki na kropki, bo to nie jest nic złego że ktoś spróbował dodać zduplikowane imię.

**Comment by Danon** [comment]
Due date changes to: 23:00 26.10.219

**Comment by Danon** [comment]
Due date changes to 21:00 02.11.2019

**Comment by Danon** [comment]
![image](https://user-images.githubusercontent.com/13367735/67796189-daca6a80-fa7f-11e9-8eee-dc1570714f22.png)
Pierwsze zrobione, drugie nie. Dalej widzę komunikaty z wykrzyknikami

**Comment by Danon** [comment]
Zamień komunikat "Invalid command!" na "Command {wstaw} is not found.".

**Comment by Danon** [comment]
I zrób żeby klikanie entera podczas podania pustego iminia i pustej komendy nic nie wypisało.
Ma się po prostu dać kliknąć enter, ma poprosić o ponowne wpisanie ale nie powinno pokazać "Empty name"

**Comment by fuzionu** [comment]
everything done
